### ISSUE TITLE
Integrate sign in component with the backend

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#199]
## Task
Currently, we're mocking the logged user with dummy data. Since we already have the backend implemented, let's hit the actual backend and use its return data to store the credentials on the local store. All the frontend logic has been already implemented, we just need to hit the real endpoint and call `auth.signIn(...)` with the returned data.

Endpoint -> `POST /api/v1/auth/signIn`

## Requirements
- [x] Dispatch a request to sign the user in
- [x] After logging in, the user is redirected to the app home screen
- [x] Handle network errors
- [ ] Add unit tests

**Comment by deepanshu0304** [comment]
Hi Please assign this task to me. I will be able to handle this.

**Comment by belgamo** [comment]
Hello @deepanshu0304, any updates here? Can I assign it to someone else?
