### ISSUE TITLE
Fix bugs on user sign-up flow

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#214]
## Description
To continue the work started on #202.

Several bugs and typescript errors in the sign-up flow need to be fixed so that user can be able to register themselves successfully. Also, since https://github.com/animavita/animavita/pull/206 has been merged which means we can log the user in effortlessly right after the registration by persisting user credentials on `AuthContext`.

## Tasks
- [x] Email field should be lowercase
- [x] Password field should hide typing
- [x] Log in the user smoothly

**Comment by gustavokenzo1** [comment]
Hi! I am looking for a project as part of an assignment of my Software Testing classes in university, in which I need to implement/improve an issue by using Test Driven Development. Do you reckon this would be a good issue?

**Comment by belgamo** [comment]
> Hi! I am looking for a project as part of an assignment of my Software Testing classes in university, in which I need to implement/improve an issue by using Test Driven Development. Do you reckon this would be a good issue?

Yes. BTW, you have good examples of how to write tests for this functionality in the `RegisterAdoptionForm`.

**Comment by gustavokenzo1** [comment]
Great! Can you assign this issue to me then? Thanks!
